name: workflow name

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage
      - name: awscodedeploy
        uses: sourcetoad/aws-codedeploy-action@v1.1.0
        with:
          # AWS Access Key
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS Secret Key
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS Region
          aws_region: us-east-1 # optional, default is us-east-1
          # S3 Bucket for CodeDeploy Assets
          s3_bucket: gitdeploy
          # S3 Folder for ZIP.
          s3_folder: app
          # Directory to be archived instead of entire workspace.
          directory: /dist # optional
          # Zip to be used for deployment, instead of archiving a directory.
          archive: # optional
          # Files to be excluded during archiving (space delimited).
          excluded_files: # optional
          # AWS CodeDeploy Application Name
          codedeploy_name: appdev
          # AWS CodeDeploy Application Group
          codedeploy_group: deploygroup_dev
          # Whether to register the deployment (vs automatic deploy).
          codedeploy_register_only: # optional, default is false
          # Max amount of iterations (15s increments) to wait for a deployment
          max_polling_iterations: # optional, default is 60
          # Whether to skip all AWS related steps.
          dry_run: # optional, default is false
